CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY CLUSTERED IDENTITY (1, 1),
	[IdentityIdentifier] NVARCHAR(MAX) NOT NULL,
	[Guid] UniqueIdentifier NOT NULL UNIQUE DEFAULT NEWID(),
	[CreatedAtDateTimeUTC] DateTime NOT NULL DEFAULT GETUTCDATE()
)
